services:
  # db:
  #   image: postgres
  #   volumes:
  #     - ./tmp/db:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_PASSWORD: password
  web:
    build: .
    command: bash -c "rerun --background 'ruby src/app.rb -o 0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "4567:4567"
    # depends_on:
    #   - db